baseURL = "/"
title = "我的科研主页"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
paginate = 10

[params]
  homeInfoParams = {Title = "Pides科研主页", Content = "华中科技大学能源学院在读博士生，欢迎访问我的科研记录站"}
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  math = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "技术笔记"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "科研项目"
    url = "/projects/"
    weight = 2
   [[menu.main]]
  identifier = "notion"
  name = "实验室日志 (Notion)"
  url = "https://www.notion.so/你的页面ID" # 这里替换为你的Notion链接
  weight = 3

